spring.application.name=firstspringboot

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

spring.datasource.url=jdbc:mariadb://localhost:3307/firstspringboot
spring.datasource.username=firstspringbootmariadbuser
spring.datasource.password=firstspringbootmariadbpassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=none

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/firstspringbootrealm
