spring.application.name=firstspringboot

app.display.null-value=<NULL>

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

spring.datasource.url=jdbc:mariadb://localhost:3307/firstspringboot
spring.datasource.username=firstspringbootmariadbuser
spring.datasource.password=firstspringbootmariadbpassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=none

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/firstspringbootrealm

keycloak.admin.server-url=http://localhost:8081
keycloak.admin.realm=master
keycloak.admin.target-realm=firstspringbootrealm
keycloak.admin.username=firstspringbootkeycloakadmin
keycloak.admin.password=firstspringbootkeycloakadminpassword
keycloak.admin.client-id=admin-cli

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadminpassword
minio.bucket=firstspringboot
