spring.application.name=firstspringboot

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

spring.datasource.url=jdbc:mariadb://localhost:3307/firstspringboot
spring.datasource.username=firstspringbootmariadbuser
spring.datasource.password=firstspringbootmariadbpassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=none

spring.security.oauth2.client.provider.firstspringbootrealm.issuer-uri=http://localhost:8080/realms/firstspringbootrealm

spring.security.oauth2.client.registration.keycloak.provider=firstspringbootrealm
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-id=firstspringbootauthclient
spring.security.oauth2.client.registration.keycloak.client-secret=ITteLUdoYtnJQpKyax5dNBr0ztodLnVG
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/firstspringbootrealm
